//-----------------------------------------------------------------------
// <auto-generated> 
// This code was generated by a HEOS.Tools.RCG. 
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated.
// 
// Based on specification version: 1.17
// Specification address: https://rn.dmglobal.com/usmodel/HEOS_CLI_ProtocolSpecification-Version-1.17.pdf
// </auto-generated> 
//-----------------------------------------------------------------------

#nullable enable

using System.CodeDom.Compiler;
using Newtonsoft.Json;
using Heos.API.JsonConverters;

namespace Heos.API.Models.HEOS.Player;

[GeneratedCode("Heos.Tools.ClassGenerator", "0.1.1")]
public partial class GetPlayersRequest : HeosRequest
{
    public GetPlayersRequest()
    {
        Command = "player/get_players";
        Parameters = new();
    }
}

[GeneratedCode("Heos.Tools.ClassGenerator", "0.1.1")]
[JsonConverter(typeof(JsonPathConverter))]
public partial class GetPlayersResponse : HeosResponse
{
	[JsonProperty("payload")]
	public List<GetPlayersResponsePayload>? Payload { get; set; }
}

[GeneratedCode("Heos.Tools.ClassGenerator", "0.1.1")]
[JsonConverter(typeof(JsonPathConverter))]
public partial class GetPlayersResponsePayload
{
	[JsonProperty("name")] public string? Name { get; set; }
	[JsonProperty("pid")] public string? Pid { get; set; }
	[JsonProperty("gid")] public string? Gid { get; set; }
	[JsonProperty("model")] public string? Model { get; set; }
	[JsonProperty("version")] public string? Version { get; set; }
	[JsonProperty("network")] public string? Network { get; set; }
	[JsonProperty("lineout")] public string? Lineout { get; set; }
	[JsonProperty("control")] public string? Control { get; set; }
	[JsonProperty("serial")] public string? Serial { get; set; }
	[JsonProperty("ip")] public string? Ip { get; set; }
}