//-----------------------------------------------------------------------
// <auto-generated> 
// This code was generated by a HEOS.Tools.RCG. 
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated.
// 
// Based on specification version: 1.17
// Specification address: https://rn.dmglobal.com/usmodel/HEOS_CLI_ProtocolSpecification-Version-1.17.pdf
// </auto-generated> 
//-----------------------------------------------------------------------

#nullable enable

using System.CodeDom.Compiler;

namespace Heos.API.Models.HEOS.Player;

[GeneratedCode("Heos.Tools.ClassGenerator", "0.1.1")]
public partial class SetQuickselectRequest : HeosRequest
{
    public SetQuickselectRequest(string pid, string id)
    {
        Command = "player/set_quickselect";
        Parameters = new()
		{
			["pid"] = pid,
			["id"] = id
		};
    }
}