namespace Heos.Tools.ClassGenerator.Constants;

public class ClassConstants
{
    /// <summary>
    /// Expected parameters:<br/>
    /// 0 - specification version and URL<br/>
    /// 1 - additional usings<br/>
    /// 2 - namespace
    /// </summary>
    public const string ClassHeader =
        """
        //-----------------------------------------------------------------------
        // <auto-generated> 
        // This code was generated by a HEOS.Tools.RCG. 
        // 
        // Changes to this file may cause incorrect behavior and will be lost if 
        // the code is regenerated.{0}
        // </auto-generated> 
        //-----------------------------------------------------------------------
        
        #nullable enable
        
        using System.CodeDom.Compiler;{1}
        
        namespace {2};
        
        
        """;

    /// <summary>
    /// Expected parameters:<br/>
    /// 0 - project name<br/>
    /// 1 - project version<br/>
    /// 2 - class name<br/>
    /// 3 - constructor parameters<br/>
    /// 4 - endpoint string<br/>
    /// 5 - parameter initialization within constructor
    /// </summary>
    public const string RequestClassTemplate =
        """
        [GeneratedCode("{0}", "{1}")]
        public partial class {2}Request : HeosRequest
        {
            public {2}Request({3})
            {
                Command = "{4}";
                Parameters = new(){5};
            }
        }
        """;

    /// <summary>
    /// Expected parameters:<br/>
    /// 0 - project name<br/>
    /// 1 - project version<br/>
    /// 2 - class name<br/>
    /// 3 - properties
    /// </summary>
    public const string ResponseClassTemplate =
        """
        
        
        [GeneratedCode("{0}", "{1}")]
        [JsonConverter(typeof(JsonPathConverter))]
        public partial class {2}Response : HeosResponse
        {{3}}
        """;

    /// <summary>
    /// Expected parameters:<br/>
    /// 0 - project name<br/>
    /// 1 - project version<br/>
    /// 2 - class name<br/>
    /// 3 - properties
    /// </summary>
    public const string ResponsePayloadClassTemplate =
        """
        
        
        [GeneratedCode("{0}", "{1}")]
        [JsonConverter(typeof(JsonPathConverter))]
        public partial class {2}ResponsePayload
        {{3}}
        """;

    /// <summary>
    /// Expected parameters:<br/>
    /// 0 - JSON name<br/>
    /// 1 - property name
    /// </summary>
    public const string ResponsePropertyTemplate = "\t[JsonProperty(\"{0}\")] public string? {1} { get; set; }\n";
}