//-----------------------------------------------------------------------
// <auto-generated> 
// This code was generated by a HEOS.Tools.RCG. 
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated.
// 
// Based on specification version: 1.17
// Specification address: https://rn.dmglobal.com/usmodel/HEOS_CLI_ProtocolSpecification-Version-1.17.pdf
// </auto-generated> 
//-----------------------------------------------------------------------

#nullable enable

using System.CodeDom.Compiler;

namespace Heos.API.Models.HEOS.System;

[GeneratedCode("Heos.Tools.ClassGenerator", "0.1.1")]
public partial class RegisterForChangeEventsRequest : HeosRequest
{
    public RegisterForChangeEventsRequest(string enable)
    {
        Command = "system/register_for_change_events";
        Parameters = new()
		{
			["enable"] = enable
		};
    }
}