namespace Heos.Tools.RCG.Constants;

public class ClassConstants
{
    /// <summary>
    /// String.Format expected parameters:<br/>
    /// 0 - namespace<br/>
    /// 1 - name<br/>
    /// 2 - constructor parameters<br/>
    /// 3 - endpoint string<br/>
    /// 4 - parameter initialization within constructor<br/>
    /// 5 - project name<br/>
    /// 6 - project version
    /// </summary>
    public const string RequestClassTemplate =
        """
        //-----------------------------------------------------------------------
        // <auto-generated> 
        // This code was generated by a HEOS.Tools.RCG. 
        // 
        // Changes to this file may cause incorrect behavior and will be lost if 
        // the code is regenerated. 
        // </auto-generated> 
        //-----------------------------------------------------------------------

        using System.CodeDom.Compiler;
        
        namespace {0};

        [GeneratedCode("{5}", "{6}")]
        public partial class {1}Request : HeosRequest
        {
            public {1}Request({2})
            {
                Command = "{3}";
                Parameters = new(){4};
            }
        }
        """;
}