<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishAot>false</PublishAot>
        <InvariantGlobalization>true</InvariantGlobalization>
        <AssemblyName>heos</AssemblyName>
        <AssemblyVersion>0.1.0</AssemblyVersion>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <DocumentationFile></DocumentationFile>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Heos.API\Heos.API.csproj" />
      <ProjectReference Include="..\Heos.Common\Heos.Common.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.1" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.1" />
    </ItemGroup>

    <ItemGroup>
      <None Update="config">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>